### ISSUE TITLE
Transfer Build To Gulp

### ISSUE THREAD

**Issue by epicmiller** [epicmiller/rebound#35]
Lets kick Grunt to the curb and start using a build tool thats not painful!

  - Use [9to5](http://6to5.org/) for transpiling
  - Use Almond for packaging the concatted lib files
  - Output: 
    - amd
      - ```AMD Files Here```
    - cjs
      - ```CJS Files Here```
    - ```rebound.runtime.js```
    - ```rebound.runtime.min.js```
    - ```rebound.compiler.js```
    - ```rebound.compiler.min.js```

Rebound runtime does not include the HTMLBars compiler, Rebound compiler or definitions for the custom ```<rebound-element>```. It assumes pre-compiled templates from the server.

There is no ```rebound.runtime.prod.js``` because every concatted file now uses Almond.

**Comment by epicmiller** [comment]
@matthewrobb @jmeas, anything to add?

**Comment by jmeas** [comment]
Is there any reason you don't wish to output UMD? 6to5 supports that out-of-the-box. [ref](http://6to5.org/docs/usage/modules/#umd)

**Comment by epicmiller** [comment]
I have a first pass at this ready to commit once https://github.com/epicmiller/rebound/pull/36 gets pulled in.

**Comment by epicmiller** [comment]
@matthewrobb I've pulled both the computed properties update and my first pass at Gulp into master. ```rebound.compiler.js``` and ```rebound.compiler.min.js``` aren't being generated yet because they will be the by-products of your work on https://github.com/epicmiller/rebound/issues/28. I'll leave this open until they are. I think you'll find working with htmlbars and the build much nicer now :)

@jmeas I figured since we are able to generate both ```amd``` and ```cjs``` it wouldn't make much sense to generate ```umd``` as well. It has a slightly larger wrapper to accommodate both languages (extra bits to push down the pipe) and so with generated module code it seems better to just use the language we need. To me ```umd``` makes more sense for hand-written modules that need to work with both out of the box.

**Comment by matthewrobb** [comment]
@epicmiller Currently the demo doesn't compile correctly out of the box due to a missing templates subdir. Perhaps add a `.gitkeep` file in there to ensure it exists or add something to the recompile-demo task?

**Comment by matthewrobb** [comment]
With the move to 6to5 are there any ES6 features you are okay with being used and if so are there any you would prefer NOT be used?

**Comment by epicmiller** [comment]
Sorry about it not working out of the box, didn't remember to make sure the templates dir was created on first run. Heres a PR to fix the out-of-the-box bugs: https://github.com/epicmiller/rebound/pull/38

**Comment by epicmiller** [comment]
Things like Enhanced Object Literals I'm apprehensive about because support partially depends on the browser, I don't want to have to include the 6to5 polyfills for the sake of size, and subclassing ```Array```, ```Date``` and ```Element``` this early on scares me (although it may be cool to have our component objects subclass Element and literally be an instance of the custom element, I need to look into how they are doing it) 
But any other features that don't require anything from the browser or the polyfill will be okay with me until we find out they kill performance for one reason or another:
 - Arrows
 - Classes
 - Template Strings
 - Destructuring
 - Default + Rest + Spread (We may want to transfer all those ```options || (options = {})```s over asap)
 - Let & Cont
 - Iterators & For...Of
 - Generators

I may ask that we take a look at the generated code the first few times we use these to make sure 6to5 isn't doing anything stupid.

Do you have any preferences / opinions?

**Comment by epicmiller** [comment]
Take a look at that PR and merge it if you feel like it looks good

**Comment by epicmiller** [comment]
The other option though is to forgo all of them except module transpiling so we have intimate control over the size of Rebound. Arguments can be made for each.

**Comment by matthewrobb** [comment]
@epicmiller Perhaps we should turn on only those things that do not require a runtime in the options to 6to5? I am already using template strings in some stuff I am working on. My opinion is that we embrace as much of the low hanging fruit as possible.

**Comment by epicmiller** [comment]
I completly agree, best to start early. It will also give me a great excuse to really learn the new conventions :+1: 

If you have a few minutes feel free to throw up a PR for that, I need to run to a meeting unfortunately

**Comment by matthewrobb** [comment]
Check out PR https://github.com/epicmiller/rebound/pull/39 for this

**Comment by epicmiller** [comment]
This has been resolved for a while now. A different issue is now open for rebound.compiler.js
